### PR TITLE
Sifive fu540 fu740

### PR DESCRIPTION
**Pull request by rminnich**

### CODE REVIEW

**Comment by QuLogic** [comment]
Please update the `README.md` and, if necessary, `LICENSE`.

**Comment by rminnich** [comment]
Please take another look, thanks

**Comment by deadprogram** [comment]
Any love for this PR please?

**Comment by VincentDary** [comment]
SVD file contribution verified against original file provider, OK.

```text
$ git clone https://github.com/riscv-rust/fu540-pac.git
$ cd fu540-pac
$ sha512sum fu540.svd >> ../hash_fu540_fu740.txt
$ cd ..
$ git clone https://github.com/riscv-rust/fu740-pac.git
$ cd fu740-pac
$ sha512sum fu740.svd >> ../hash_fu540_fu740.txt
$ cd ..
$ git clone https://github.com/BenBE/cmsis-svd-data.git
$ cd cmsis-svd-data
$ git checkout sifive_fu540_fu740
$ cd data/SiFive-Community
$ sha512sum -c ../../../hash_fu540_fu740.txt
fu540.svd: OK
fu740.svd: OK
$ echo $?
0
```

@rminnich thank you very much for your contribution.

[hash_fu540_fu740.txt](https://github.com/user-attachments/files/17531519/hash_fu540_fu740.txt)

**Pull request closed without merging**
