### PR TITLE
Added RP2350 SVD

### PR DESCRIPTION
**Pull request by Bee4Queer**
First contribution, got SVD from [here](https://github.com/raspberrypi/pico-sdk/tree/master/src/rp2350/hardware_regs).
The RP2350 is a newly released MCU from Raspberry Pi, [released along side the Raspberry Pi Pico 2](https://www.raspberrypi.com/news/raspberry-pi-pico-2-our-new-5-microcontroller-board-on-sale-now/).

### CODE REVIEW

**Review by deadprogram — APPROVED** [review]
LGTM!

**Review by deadprogram — APPROVED** [review]

**Comment by Bee4Queer** [comment]
Hey! @VincentDary could you outline why this was closed without merging?

**Comment by VincentDary** [comment]
This is an error on my part, I am working on the [issue 4](https://github.com/cmsis-svd/cmsis-svd-data/issues/4) and I have force push on the repository, the issue has been closed automatically, I can't reopen the issue, Github block the reopen buton, but I am working to merge your commit and other closed automatically.

**Comment by BenBE** [comment]
@AverseABFun I have a branch with your commits prepared on my fork. They aren't lost. It just got too late yesterday while investigating the situation. Once the mentioned issue #4 has been resolved, we'll work on merging #5, #6, #7, #9 and this one, which were all affected. Issue #10 will receive a replacement with another implementation though (working on that one too).

**Comment by Bee4Queer** [comment]
Alright, sounds good! Thanks for informing me.

**Comment by VincentDary** [comment]
SVD file contribution verified against original file provider, OK.

```text
$ git clone https://github.com/raspberrypi/pico-sdk.git
$ cd pico-sdk/src/rp2350/hardware_regs/
$ sha512sum RP2350.svd > ../../../../hash_from_raspberrypi.txt
$ cd ../../../../
$ sed -i -e 's/RP2350.svd/rp2350.svd/g' hash_from_raspberrypi.txt
$ git clone https://github.com/BenBE/cmsis-svd-data.git
$ cd cmsis-svd-data
$ git checkout rp2350
$ cd data/RaspberryPi
$ sha512sum -c ../../../hash_from_raspberrypi.txt
rp2350.svd: OK
$ echo $?
0
```

@AverseABFun thank you very much for your contribution.


[hash_from_raspberrypi.txt](https://github.com/user-attachments/files/17531392/hash_from_raspberrypi.txt)

**Pull request closed without merging**
